In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('UCI_Credit_Card.csv')
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default.payment.next.month
0,1,20000.0,2,2,1,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,2,2,2,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,2,2,2,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,2,2,1,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,1,2,1,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [3]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  float64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  float64
 13  BILL_AMT2                   30000 non-null  float64
 14  BILL_AMT3                   30000 non-null  float64
 15  BILL_AMT4                   30000 non-null  float64
 16  BILL_AMT5                   30000 non-null  float64
 17  BILL_AMT6                   30000 non-null  float64
 18  PAY_AMT1                    30000 non-null  float64
 19  PAY_AMT2                    30000 non-null  float64
 20  PAY_AMT3                    30000 non-null  float64
 21  PAY_AMT4                    30000 non-null  float64
 22  PAY_AMT5                    30000 non-null  float64
 23  PAY_AMT6                    30000 non-null  float64
 24  default.payment.next.month  30000 non-null  int64
dtypes: float64(13), int64(12)
memory usage: 5.7 MB

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default.payment.next.month    0
dtype: int64

In [4]:
df['Total Payment'] = (
    df['PAY_0'] + df['PAY_2'] + df['PAY_3'] + df['PAY_4'] + df['PAY_5'] + df['PAY_6']
)

In [5]:
bill_cols = ['BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4','BILL_AMT5','BILL_AMT6']
df['avg_bill'] = df[bill_cols].mean(axis=1)
df['max_bill'] = df[bill_cols].max(axis=1)

pay_amt_cols = ['PAY_AMT1','PAY_AMT2','PAY_AMT3','PAY_AMT4','PAY_AMT5','PAY_AMT6']
df['total_pay_amt'] = df[pay_amt_cols].sum(axis=1)

df['util_1'] = df['BILL_AMT1'] / (df['LIMIT_BAL'] + 1)

In [6]:
X = df.drop(columns=['LIMIT_BAL', 'default.payment.next.month'], errors='ignore')
y = df['LIMIT_BAL']

In [7]:
df['SEX'].unique()
df['SEX'].nunique()

2

In [8]:
df['EDUCATION'].unique()
df['EDUCATION'].nunique()

7

In [9]:
df['MARRIAGE'].unique()
df['MARRIAGE'].nunique()

4

In [10]:
df = pd.get_dummies(df, columns=['SEX','EDUCATION','MARRIAGE'], drop_first=True)
df

,ID,LIMIT_BAL,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,...,SEX_2,EDUCATION_1,EDUCATION_2,EDUCATION_3,EDUCATION_4,EDUCATION_5,EDUCATION_6,MARRIAGE_1,MARRIAGE_2,MARRIAGE_3
0,1,20000.0,24,2,2,-1,-1,-2,-2,3913.0,...,True,False,True,False,False,False,False,True,False,False
1,2,120000.0,26,-1,2,0,0,0,2,2682.0,...,True,False,True,False,False,False,False,False,True,False
2,3,90000.0,34,0,0,0,0,0,0,29239.0,...,True,False,True,False,False,False,False,False,True,False
3,4,50000.0,37,0,0,0,0,0,0,46990.0,...,True,False,True,False,False,False,False,True,False,False
4,5,50000.0,57,-1,0,-1,0,0,0,8617.0,...,False,False,True,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,39,0,0,0,0,0,0,188948.0,...,False,False,False,True,False,False,False,True,False,False
29996,29997,150000.0,43,-1,-1,-1,-1,0,0,1683.0,...,False,False,False,True,False,False,False,False,True,False
29997,29998,30000.0,37,4,3,2,-1,0,0,3565.0,...,False,False,True,False,False,False,False,False,True,False
29998,29999,80000.0,41,1,-1,0,0,0,-1,-1645.0,...,False,False,False,True,False,False,False,True,False,False
29999,30000,50000.0,46,0,0,0,0,0,0,47929.0,...,False,False,True,False,False,False,False,True,False,False

In [11]:
df.columns

Index(['ID', 'LIMIT_BAL', 'AGE', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5',
       'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4',
       'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3',
       'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'default.payment.next.month',
       'Total Payment', 'avg_bill', 'max_bill', 'total_pay_amt', 'util_1',
       'SEX_2', 'EDUCATION_1', 'EDUCATION_2', 'EDUCATION_3', 'EDUCATION_4',
       'EDUCATION_5', 'EDUCATION_6', 'MARRIAGE_1', 'MARRIAGE_2', 'MARRIAGE_3'],
      dtype='object')

In [12]:
df = df.drop(columns = ['ID'])

In [13]:
from sklearn.model_selection import train_test_split
X_Train, X_Test, y_Train, y_Test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_Train_Scaled = scaler.fit_transform(X_Train)
X_Test_Scaled = scaler.transform(X_Test)

In [15]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model

LinearRegression()

In [26]:
lr_model.fit(X_Train_Scaled, y_Train)
lr_pred  = lr_model.predict(X_Test_Scaled)
from sklearn.metrics import r2_score
lr_acc = r2_score(y_Test, lr_pred)
print(f'accuracy: {lr_acc}')

accuracy: 0.5677955320811343

In [27]:
from sklearn.linear_model import Ridge
r_model = Ridge(alpha = 10)
r_model

Ridge(alpha=10)

In [28]:
r_model.fit(X_Train_Scaled, y_Train)
r_pred = r_model.predict(X_Test_Scaled)
from sklearn.metrics import r2_score
r_acc = r2_score(y_Test, r_pred)
print(f'accuracy: {r_acc}')

accuracy: 0.567770479346142

In [36]:
from sklearn.ensemble import RandomForestRegressor
rf_model = RandomForestRegressor(max_depth = 10, criterion = 'poisson' , random_state = 42)
rf_model

RandomForestRegressor(criterion='poisson', max_depth=10, random_state=42)

In [37]:
rf_model.fit(X_Train, y_Train)
rf_pred = rf_model.predict(X_Test)
from sklearn.metrics import r2_score
rf_acc = r2_score(y_Test, rf_pred)
print(f'accuracy: {rf_acc}')

accuracy: 0.8415241368541817

In [38]:
from sklearn.tree import DecisionTreeRegressor
dt_model = DecisionTreeRegressor(max_depth = 10, criterion = 'poisson', random_state = 42)
dt_model

DecisionTreeRegressor(criterion='poisson', max_depth=10, random_state=42)

In [39]:
dt_model.fit(X_Train, y_Train)
dt_pred = dt_model.predict(X_Test)
from sklearn.metrics import r2_score
dt_acc = r2_score(y_Test, dt_pred)
print(f"Accuracy: {dt_acc}")

Accuracy: 0.8088549887006367

In [40]:
model_accuracies={
    "LinearRegression": lr_acc,
    "Ridge": r_acc,
    "DesicionTree" : dt_acc
    "RandomForest":rf_acc
}
model_accuracies

{'Linear Regression': 0.5677955320811343,
 'Ridge': 0.567770479346142,
 'RandomForest': 0.8415241368541817}

In [41]:
best_model_name=max(model_accuracies,key=model_accuracies.get)
best_accuracy=model_accuracies[best_model_name]
print(f"\n Best Model:{best_model_name} with accuracy of {best_accuracy:4f}")

 Best Model:RandomForest with accuracy of 0.841524

In [42]:
df.head

<bound method NDFrame.head of        LIMIT_BAL  AGE  PAY_0  PAY_2  PAY_3  PAY_4  PAY_5  PAY_6  BILL_AMT1  \
0        20000.0   24      2      2     -1     -1     -2     -2     3913.0
1       120000.0   26     -1      2      0      0      0      2     2682.0
2        90000.0   34      0      0      0      0      0      0    29239.0
3        50000.0   37      0      0      0      0      0      0    46990.0
4        50000.0   57     -1      0     -1      0      0      0     8617.0
...          ...  ...    ...    ...    ...    ...    ...    ...        ...
29995   220000.0   39      0      0      0      0      0      0   188948.0
29996   150000.0   43     -1     -1     -1     -1      0      0     1683.0
29997    30000.0   37      4      3      2     -1      0      0     3565.0
29998    80000.0   41      1     -1      0      0      0     -1    -1645.0
29999    50000.0   46      0      0      0      0      0      0    47929.0

       BILL_AMT2  ...  SEX_2  EDUCATION_1  EDUCATION_2  EDUCATION_3  \
0         3102.0  ...   True        False         True        False
1         1725.0  ...   True        False         True        False
2        14027.0  ...   True        False         True        False
3        48233.0  ...   True        False         True        False
4         5670.0  ...  False        False         True        False
...          ...  ...    ...          ...          ...          ...
29995   192815.0  ...  False        False        False         True
29996     1828.0  ...  False        False        False         True
29997     3356.0  ...  False        False         True        False
29998    78379.0  ...  False        False        False         True
29999    48905.0  ...  False        False         True        False

       EDUCATION_4  EDUCATION_5  EDUCATION_6  MARRIAGE_1  MARRIAGE_2  \
0            False        False        False        True       False
1            False        False        False       False        True
2            False        False        False       False        True
3            False        False        False        True       False
4            False        False        False        True       False
...            ...          ...          ...         ...         ...
29995        False        False        False        True       False
29996        False        False        False       False        True
29997        False        False        False       False        True
29998        False        False        False        True       False
29999        False        False        False        True       False

       MARRIAGE_3
0           False
1           False
2           False
3           False
4           False
...           ...
29995       False
29996       False
29997       False
29998       False
29999       False

[30000 rows x 36 columns]>